// build.js — run with: node build.js
// Reads all YAML files in ./products/, sorts by order, writes data.js

const fs   = require('fs');
const path = require('path');
const yaml = require('js-yaml');

const productsDir = path.join(__dirname, 'products');
const outputFile  = path.join(__dirname, 'data.js');

const files = fs.readdirSync(productsDir)
  .filter(f => f.endsWith('.yaml') || f.endsWith('.yml'))
  .sort();

const categories = files.map(file => {
  const raw = fs.readFileSync(path.join(productsDir, file), 'utf8');
  return yaml.load(raw);
});

const output = `// Auto-generated by build.js — do not edit manually
// Run: node build.js

const GEAR = ${JSON.stringify(categories, null, 2)};
`;

fs.writeFileSync(outputFile, output, 'utf8');
console.log(`✓ Built data.js from ${files.length} category file(s):`);
files.forEach(f => console.log(`  · ${f}`));
