// Auto-generated by build.js — do not edit manually
// Run: node build.js

const GEAR = [
  {
    "category": "Mobile Camera Setup",
    "order": 1,
    "products": [
      {
        "name": "DJI Osmo Pocket 3",
        "desc": "Main run-and-gun camera. Incredible stabilization.",
        "ref": true,
        "links": {
          "DE": "https://amzn.to/PLACEHOLDER_DE_OP3",
          "US": "https://amzn.to/PLACEHOLDER_US_OP3",
          "UK": "https://amzn.to/PLACEHOLDER_UK_OP3"
        }
      },
      {
        "name": "DJI Mic 2",
        "desc": "Wireless mic system with built-in recorder.",
        "ref": true,
        "links": {
          "DE": "https://amzn.to/PLACEHOLDER_DE_MIC2",
          "US": "https://amzn.to/PLACEHOLDER_US_MIC2",
          "UK": "https://amzn.to/PLACEHOLDER_UK_MIC2"
        }
      },
      {
        "name": "DJI Mic Mini",
        "desc": "Smaller, lighter companion mic option.",
        "ref": true,
        "links": {
          "DE": "https://amzn.to/PLACEHOLDER_DE_MICMINI",
          "US": "https://amzn.to/PLACEHOLDER_US_MICMINI",
          "UK": "https://amzn.to/PLACEHOLDER_UK_MICMINI"
        }
      },
      {
        "name": "Sony FX3",
        "desc": "Primary camera body. Cinema line, full frame.",
        "ref": true,
        "links": {
          "DE": "https://amzn.to/PLACEHOLDER_DE_FX3",
          "US": "https://amzn.to/PLACEHOLDER_US_FX3",
          "UK": "https://amzn.to/PLACEHOLDER_UK_FX3"
        }
      },
      {
        "name": "Sony A7C II",
        "desc": "Compact second body with DJI Mic 2 MI Shoe support.",
        "ref": true,
        "links": {
          "DE": "https://amzn.to/PLACEHOLDER_DE_A7CII",
          "US": "https://amzn.to/PLACEHOLDER_US_A7CII",
          "UK": "https://amzn.to/PLACEHOLDER_UK_A7CII"
        }
      },
      {
        "name": "Teenage Engineering CM-15",
        "desc": "Compact cardioid mic — surprisingly great on desk.",
        "ref": false,
        "global_link": "https://teenage.engineering/products/cm-15",
        "global_store": "teenage.engineering"
      }
    ]
  },
  {
    "category": "Streaming & Audio",
    "order": 2,
    "products": [
      {
        "name": "Audio Interface",
        "desc": "Add your actual interface here.",
        "ref": true,
        "links": {
          "DE": "https://amzn.to/PLACEHOLDER_DE_AI",
          "US": "https://amzn.to/PLACEHOLDER_US_AI",
          "UK": "https://amzn.to/PLACEHOLDER_UK_AI"
        }
      },
      {
        "name": "Boom Arm",
        "desc": "Add your actual boom arm here.",
        "ref": true,
        "links": {
          "DE": "https://amzn.to/PLACEHOLDER_DE_BOOM",
          "US": "https://amzn.to/PLACEHOLDER_US_BOOM",
          "UK": "https://amzn.to/PLACEHOLDER_UK_BOOM"
        }
      }
    ]
  },
  {
    "category": "Lighting",
    "order": 3,
    "products": [
      {
        "name": "Key Light",
        "desc": "Add your light here.",
        "ref": true,
        "links": {
          "DE": "https://amzn.to/PLACEHOLDER_DE_LIGHT",
          "US": "https://amzn.to/PLACEHOLDER_US_LIGHT",
          "UK": "https://amzn.to/PLACEHOLDER_UK_LIGHT"
        }
      }
    ]
  },
  {
    "category": "Music & Synths",
    "order": 4,
    "products": [
      {
        "name": "Eurorack Case",
        "desc": "Add your case here.",
        "ref": true,
        "links": {
          "DE": "https://amzn.to/PLACEHOLDER_DE_CASE",
          "US": "https://amzn.to/PLACEHOLDER_US_CASE",
          "UK": "https://amzn.to/PLACEHOLDER_UK_CASE"
        }
      },
      {
        "name": "Patch Cables",
        "desc": "Add your cable brand here.",
        "ref": true,
        "links": {
          "DE": "https://amzn.to/PLACEHOLDER_DE_CABLES",
          "US": "https://amzn.to/PLACEHOLDER_US_CABLES",
          "UK": "https://amzn.to/PLACEHOLDER_UK_CABLES"
        }
      }
    ]
  }
];
